
require('./assets/Scripts/AD/AD_ROOT');
require('./assets/Scripts/AD/Global');
require('./assets/Scripts/AD/PlatformBase');
require('./assets/Scripts/AD/weChatPlatform');
require('./assets/Scripts/Main/Entry');
require('./assets/Scripts/Main/Load');
require('./assets/Scripts/Main/Main');
require('./assets/Scripts/Main/ResMgr');
require('./assets/Scripts/Main/achievement');
require('./assets/Scripts/Main/condition');
require('./assets/Scripts/Main/evenList');
require('./assets/Scripts/Main/summary');
require('./assets/Scripts/Other/Box');
require('./assets/Scripts/Other/DataBase');
require('./assets/Scripts/Other/GlobalDefine');
require('./assets/Scripts/Other/SaveUtils');
require('./assets/Scripts/Other/ScrollviewMgr');
require('./assets/Scripts/Other/UserModel');
